CREATE TABLE "resume_histories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resume_id" int NOT NULL,
  "stage_id" int NOT NULL,
  "start_time" timestamp NOT NULL DEFAULT (now()),
  "end_time" timestamp,
  "user_id" int NOT NULL
);

CREATE INDEX ON "resume_histories" ("resume_id");
CREATE INDEX ON "resume_histories" ("stage_id");