CREATE TABLE "resumes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vacancy_id" int NOT NULL,
  "current_stage_id" int NOT NULL,
  "candidate_name" varchar(255) NOT NULL,
  "candidate_contact" text NOT NULL,
  "source" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "resumes" ("vacancy_id");
CREATE INDEX ON "resumes" ("current_stage_id");