CREATE TABLE "stages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" resume_stages UNIQUE NOT NULL
);

INSERT INTO stages (name) VALUES 
    ('opened'),
    ('studied'),
    ('interview'),
    ('passed_interview'),
    ('technical_interview_scheduled'),
    ('technical_interview_passed'),
    ('offer_sent');